# Configurações de memória para build Android
org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8

# Sem daemon para economizar memória
org.gradle.daemon=false
org.gradle.caching=false
org.gradle.parallel=false

# Android
android.useAndroidX=true
android.enableJetifier=false

# Kotlin
kotlin.code.style=official
